version: '3.0'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: unless-stopped
    privileged: true

    networks:
      localnet:
        ipv4_address: 10.12.14.16
        aliases:
          - gitlab.localhost
          - registry.localhost
          - mattermost.localhost

    ports:
      - "127.0.0.1:2222:22"
      - "127.0.0.1:80:80"
      - "127.0.0.1:5000:5000"

    volumes:
      - gitlab_data:/var/opt/gitlab
      - ./backups:/var/opt/gitlab/backups
      - ./gitlab:/etc/gitlab

    tmpfs:
      - /prometheus


  runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped

    depends_on:
      - dind
      - gitlab

    environment:
      DOCKER_HOST: "tcp://dind:2375"

    networks:
      localnet:

    volumes:
      - ./runner:/etc/gitlab-runner


  dind:
    image: docker:dind
    command: [ '--insecure-registry', 'registry.localhost' ]
    privileged: true
    restart: unless-stopped

    networks:
      localnet:

    volumes:
      - dind_data:/var/lib/docker
      - dind_cache:/cache


volumes:
  dind_data:
  dind_cache:
  gitlab_data:


networks:
  localnet:
    ipam:
      config:
        - subnet: 10.12.14.0/24
