version: '3.0'

services:

  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: "gitlab.localhost"
    restart: unless-stopped
    ports:
      - "127.0.0.1:2222:22"
      - "127.0.0.1:80:80"
      - "127.0.0.1:5000:5000"
    volumes:
      - ./gitlab:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
      - ./backups:/var/opt/gitlab/backups
    tmpfs:
      - /prometheus
    networks:
      default:
        ipv4_address: 10.12.14.16
        aliases:
          - gitlab.localhost

  runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    volumes:
      - ./runner:/etc/gitlab-runner:ro
    environment:
      DOCKER_HOST: "tcp://dind:2375"
    depends_on:
      - dind
      - gitlab

  dind:
    image: docker:dind
    restart: unless-stopped
    privileged: true
    command: [ '--insecure-registry', 'gitlab.localhost:5000' ]
    volumes:
      - dind_data:/var/lib/docker

volumes:
  dind_data:
  gitlab_data:

networks:
  default:
    ipam:
      config:
        - subnet: 10.12.14.0/24
